### ISSUE TITLE
Equipo incompleto

### ISSUE THREAD

**Issue by jorgaf** [Jorgeflowers18/proyectoPAvanzada#2]
Revisen los miembros del equipo, no creo que están todos. No se olviden de incluir en su proyecto para poder realizar de mejor manera el seguimiento del proyecto.

**Comment by Jorgeflowers18** [comment]
Listo ingeniero, al parecer aun faltaba de aceptar la invitación mi compañero, por eso no aparecía.

**Comment by jorgaf** [comment]
Sigo sin poder asignar los issues, por favor volver a enviar la invitación.
